codecov:
  require_ci_to_pass: true
  strict_yaml_branch: main

coverage:
  precision: 2
  round: down
  range: "75...90"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 90%
        base: auto
