linters:
  # Disable all default linters and enable only revive and formatters before
  # new findings by default linters are addressed.
  disable-all: true
  enable:
    - gofumpt
    - goimports
    - revive

issues:
  exclude-use-default: false

linters-settings:
  revive:
    confidence: 0.8
    ignore-generated-header: false
    severity: error

    rules:
      - name: blank-imports
      - name: confusing-naming
      - name: confusing-results
      - name: context-as-argument
      - name: context-keys-type
      - name: deep-exit
      - name: dot-imports
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: get-return
      - name: if-return
      - name: import-shadowing
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: struct-tag
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: var-declaration
      - name: var-naming
