codecov:
  require_ci_to_pass: yes
  strict_yaml_branch: master

coverage:
  precision: 2
  round: down
  range: "75...90"
  status:
    project:
      target: 80%
      threshold: 5%
      base: auto
