name: "Go: Lint"
on:
  workflow_call: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod


      - name: Run golangci-lint
        id: golangci-lint
        uses: golangci/golangci-lint-action@v8
