name: "Go: Lint"
on:
  workflow_call: {}

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod

      - uses: actions/checkout@v4

      - name: Run golangci-lint
        id: golangci-lint
        uses: golangci/golangci-lint-action@v3
